src/django_project/apps/core/urls.py
from django.urls import path
from django_project.apps.core import views

app_name = 'core'


urlpatterns = [
    path('home/', views.homepage, name='homepage'),
    path('profile/', views.profile, name='myprofile'),
    path('accept_terms/', views.accept_terms, name='acceptterms'),
    path('preregister/', views.producers_pre_register, name='preregister'),
    path('activate/<int:user_id>', views.activate_user, name='activate_user'),
    path('faq/', views.faq, name='faq'),
    path('message/<int:event_id>', views.send_message, name='sendmessage'),
    path('message/<int:comment_id>/delete/<int:event_id>', views.delete_message, name='deletemessage'),

    # musician-event confirmation / refusal
    path('musicianevent/confirmation/<int:musician_event_id>', views.add_musicians_confirmation, name='musicianconfirmation'),
    path('musicianevent/refusal/<int:musician_event_id>', views.add_musicians_refusal, name='musicianrefusal'),

    # musician related urls
    path('musician/management/', views.create_or_edit_musician, name='musicianmanagement'),
    path('musician/list/', views.musicians_list, name='musicianslist'),
    path('musician/delete/<int:musician_id>/', views.delete_musician, name='musiciandelete'),
    path('musician/addto/<int:event_id>/', views.add_musicians, name='addmusicians'),
    path('references/manage/<int:event_id>/', views.set_references_for_musicians, name='managereferencesforevent'),

    # event related urls
    path('event/history/', views.pastevents, name='pastevents'),
    path('event/<int:event_id>/', views.event, name='event'),
    path('event/new/', views.new_event, name='newevent'),
    path('event/confirm/<int:event_id>/', views.event_confirmed, name='eventconfirmed'),
    path('event/cancel/<int:event_id>/', views.event_cancelled, name='eventcancelled'),
    path('event/conclude/<int:event_id>/', views.conclude_event, name='eventconcluded'),
    path('event/paid/<int:event_id>/', views.event_paid, name='paymentconfirmed'),
    path('event/refused/<int:event_id>/', views.event_refused, name='refuseparticipation'),

    # artist song-management related urls
    path('song/list/', views.my_songs, name='my_songs'),
    path('song/manage/', views.manage_songs, name='songmanagement'),
    path('song/delete/<int:song_id>/', views.song_delete, name='songdelete'),
]

src/django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.utils.translation import ugettext as _
from django.shortcuts import render

admin.site.site_header = _('Gig2You - Administration')


def home(request):
    if request.user.is_staff:
        return redirect('admin:index')
    elif request.user.is_authenticated:
        return redirect('core:homepage')
    return render(request, 'core/other/index.html')


def contact(request):
    return render(request, 'core/other/contact.html')


def about(request):
    return render(request, 'core/other/about.html')

urlpatterns = [

    url(r'^impersonate/', include('impersonate.urls')),

    path('admin/', admin.site.urls, name='admin'),  # admin site

    path('', home, name='homepage'),
    path('about/', about, name='about'),

    path('app/', include('django_project.apps.core.urls', namespace='core')),
    path('contact/', contact, name='contact'),
    # auth
    path('accounts/login/',
         auth_views.LoginView.as_view(template_name='auth/login.html', redirect_authenticated_user=True),
         name='login'),

    path('logout/', auth_views.LogoutView.as_view(template_name='auth/logout.html'), name='logout'),

    # password reset
    path(
        'accounts/login/password_reset/',
        auth_views.PasswordResetView.as_view(template_name='auth/reset_form.html'),
        name='password_reset',
    ),
    path(
        'accounts/login/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name="auth/reset_done.html"),
        name='password_reset_done',
    ),
    path(
        'accounts/login/reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="auth/reset_confirm.html"),
        name='password_reset_confirm',
    ),
    path(
        'accounts/login/reset/done/',
        auth_views.PasswordResetCompleteView.as_view(template_name="auth/reset_complete.html"),
        name='password_reset_complete',
    ),
]

src/django_project/apps/core/views.py
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist, FieldError
from django.db.models import Q
from django.http import HttpResponseNotFound, HttpResponseForbidden, HttpResponse, HttpResponseBadRequest, \
    HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from post_office import mail

from django_project.apps.core.models.base import ArtistSong, EventSong, FaqModel, Comment, has_accepted_use_terms
from .decorators import user_has_accepted_use_terms
from .forms import RawEventForm, CreateMusicianForm, UserForm, MusicianEventFormSetFactory, ArtistReferenceForm, \
    EventReferenceForm, CommentForm, UserBaseForm, ConcludeEventFormset, PostEventCommentForm
from django.utils.translation import ugettext as _

from .models import Event, Musician, MusicDirector, Artist, Producer, get_user_type, MusicianEvent, ArtistSong, \
    EventSong
from ...settings.terms_of_service import get_terms


# retorna o nivel de importancia do Faq, para fins de ordenação
def get_faq_importance(FaqModel):
    return FaqModel.importance


# retorna a data de criação do comentario
def get_date_order(Comment):
    return Comment.created_date


def faq(request):
    """
        Renders the FAQ page
    """
    context = dict()
    faqs = sorted(FaqModel.objects.all(), key=get_faq_importance)
    context['faqs'] = faqs
    return render(request, 'core/other/faq.html', context=context)


def producers_pre_register(request):
    """
        Faz o pre cadastro dos contratantes. O usuario eh criado como inativo ate que o SuperUsuario o avalie e ative
    """
    context = dict()
    if request.method == 'POST':
        form = UserBaseForm(data=request.POST)
        if form.is_valid():
            try:
                if not form.cleaned_data['password']:
                    raise FieldError
                user = User.objects.create(username=form.cleaned_data['email'], email=form.cleaned_data['email'],
                                           first_name=form.cleaned_data['name'], is_active=False)
                user.set_password(form.cleaned_data['password'])
                user.save()
                Producer.objects.create(
                    user_id=user.id,
                    phone=form.cleaned_data['phone'],
                    whatsapp=form.cleaned_data['whatsapp'],
                    address=form.cleaned_data['address'],
                    cep=form.cleaned_data['cep'],
                    doc_number=form.cleaned_data['doc_number'],
                    name=form.cleaned_data['name'],
                    email=form.cleaned_data['email'],
                )
                messages.success(request, _(
                    'Your profile has been submitted successfully! Our team will analyse it and you will receive an email if it is approved.'),
                                 extra_tags='alert')
            except FieldError:
                messages.warning(request, _('Password field is mandatory.'), extra_tags='alert')
        else:
            messages.warning(request, _('Fix the validation errors below before saving!'), extra_tags='alert')
    else:
        form = UserBaseForm()
    context['form'] = form
    return render(request, 'core/other/pre_register.html', context=context)


@login_required
@staff_member_required
def activate_user(request, user_id):
    """
        O SuperUsuario deve ativar usuarios de contratantes feitos atraves do pre-cadastro.
        Esta view eh ligada no admin do Produtor
    """
    user = User.objects.get(id=user_id)
    user.is_active = True
    user.save()
    send_mail_user_active(user.email, request)
    # redirecionando especificamente de volta para a pagina de edicao daquele produtor no admin
    # a funcao recebe como parametro uma string, e esta string eh prenchida com dados informados pelo format
    return HttpResponseRedirect(
        '{}producer/{}/change/'.format(request.build_absolute_uri(reverse('admin:app_list', args=('core',))),
                                       Producer.objects.get(user=user).id))


# ----------------------------
# MAIN views - comuns a todos
# ----------------------------
@login_required
def accept_terms(request):
    """
        Aceita os termos e condicoes de uso
    """
    user_type = get_user_type(request.user)
    user = User.objects.get(id=request.user.id)
    try:
        if user_type == 'artist':
            Artist.objects.get(user=user).accept_use_terms()
        if user_type == 'producer':
            Producer.objects.get(user=user).accept_use_terms()
        if user_type == 'musician':
            Musician.objects.get(user=user).accept_use_terms()
        if user_type == 'music_director':
            MusicDirector.objects.get(user=user).accept_use_terms()
    except ObjectDoesNotExist as e:
        return HttpResponse(e)
    return redirect('core:homepage')


@login_required
def homepage(request):
    """
        Renders the homepage
    """
    context = dict()
    user_type = get_user_type(request.user)
    context['user_type'] = user_type
    context['terms'] = get_terms(user_type)
    # exibe o modal de termos de uso caso o usuario ainda nao tenha aceito
    context['has_not_accepted_use_terms'] = not has_accepted_use_terms(request.user.id)
    # o conteudo do contexto varia para cada user type
    if user_type == 'artist':
        context['events'] = Event.objects.filter(
            Q(artist__user_id=request.user.id) | Q(producer__user_id=request.user.id))
        context['self'] = Artist.objects.get(user_id=request.user.id)
    elif user_type == 'producer':
        context['events'] = Event.objects.filter(producer__user_id=request.user.id)
        context['self'] = Producer.objects.get(user_id=request.user.id)
    elif user_type == 'music_director':
        music_director = MusicDirector.objects.get(user_id=request.user.id)
        context['events'] = music_director.event_set.all()
        context['musicians'] = music_director.musician_set.all()
        context['self'] = MusicDirector.objects.get(user_id=request.user.id)
    elif user_type == 'musician':
        # musician = Musician.objects.get(user_id=request.user.id)
        # musician_events = musician.musicianevent_set.prefetch_related().all()
        musician_events = MusicianEvent.objects.filter(musician__user_id=request.user.id).prefetch_related()
        context['musician_events'] = musician_events
        events = []
        for musician_event in musician_events:
            events.append(musician_event.event)
        context['events'] = events
        context['self'] = Musician.objects.get(user_id=request.user.id)

    # as particularidades de cada usuario no template sao tratadas dentro do mesmo
    return render(request, 'core/other/loggedhomepage.html', context=context)


@login_required
@user_has_accepted_use_terms
def profile(request):
    """
        Renders the profile template
    """
    user_type = get_user_type(request.user)
    if request.method == 'POST':
        # artistas tem que ver um template um pouco diferente, por causa da aceitacao de musicos
        is_artist = False
        if user_type == 'artist':
            is_artist = True
        form = UserForm(is_artist=(user_type == 'artist'), data=request.POST)
        if form.is_valid():
            user = User.objects.get(id=request.user.id)
            # user.email = form.cleaned_data['email']
            # user.username = form.cleaned_data['email']
            # user.first_name = form.cleaned_data['name']
            from django_project.apps.core.models.base import set_user_attribute
            set_user_attribute(request.user, 'email', form.cleaned_data['email'])
            set_user_attribute(request.user, 'name', form.cleaned_data['name'])
            set_user_attribute(request.user, 'phone', form.cleaned_data['phone'])
            set_user_attribute(request.user, 'address', form.cleaned_data['address'])
            set_user_attribute(request.user, 'cep', form.cleaned_data['cep'])
            set_user_attribute(request.user, 'doc_number', form.cleaned_data['doc_number'])

            if user_type == 'artist':
                set_user_attribute(request.user, 'phone', form.cleaned_data['phone'])
                set_user_attribute(request.user, 'accept_v', form.cleaned_data['accept_v'])
                set_user_attribute(request.user, 'accept_g', form.cleaned_data['accept_g'])
                set_user_attribute(request.user, 'accept_b', form.cleaned_data['accept_b'])
                set_user_attribute(request.user, 'accept_t', form.cleaned_data['accept_t'])
                set_user_attribute(request.user, 'accept_bt', form.cleaned_data['accept_bt'])
                set_user_attribute(request.user, 'accept_bvt', form.cleaned_data['accept_bvt'])
                set_user_attribute(request.user, 'accept_bvs', form.cleaned_data['accept_bvs'])
                set_user_attribute(request.user, 'accept_bvc', form.cleaned_data['accept_bvc'])

            if form.cleaned_data['password'] and form.cleaned_data['password'] != '':
                user.set_password(form.cleaned_data['password'])
            messages.success(request, _('Your profile has been updated successfully!'), extra_tags='alert')
            user.save()
    else:
        from django_project.apps.core.models.base import get_user_attribute
        # from django.http import HttpResponse
        if request.user.is_authenticated:
            initial = dict(
                user_id=request.user.id,
                email=request.user.get_username(),
                name=request.user.get_full_name(),
                whatsapp=get_user_attribute(request.user, 'whatsapp'),
                phone=get_user_attribute(request.user, 'phone'),

src/django_project/apps/core/templates/core/other/contact.html
{% extends 'core/base/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load static %}
{% block extra_css %}
{{ form.media }}
    <style>
    .fa{
        color: #39b54a;
        font-size: 65px;
    }
    .fa:hover {
        color: #09581f;
    }

	body{
		background-color: #363636;
		color: #ededed;
	}
    </style>
{% endblock %}
{% block content %}
    <main id="main">
        <!-- start of main banner -->
        <div class="container">
            <div class="col-xs-12 col-md-10 pad-top-lg pad-bottom-lg col-md-offset-1">
                <header class="main-heading text-center row">
                    <div class="col-xs-12"><br>

                        <img id="comp-iggmnz6timgimage" style="object-position: 50% 50%; width: 255px; height: 206px; object-fit: cover;" alt="conect.png" data-type="image" itemprop="image" src="https://static.wixstatic.com/media/8d0b80_bb6ef76f8b7640d483a6c02bb78a6e03~mv2.png/v1/fill/w_510,h_412,al_c,q_80,usm_0.66_1.00_0.01/conect.webp">
                        <br>
                        <br>
                        <h2 class="heading" style="color: #ededed;"> {% trans 'Contact us' %} </h2>
                        <hr style="border-top: 3px solid #38892f" width="80px">
                    </div>
                </header>
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3">
                        <p class="text-center">
                            <a href="mailto:guigyoumusic@gmail.com?Subject=About%20GuigYou" style="color:#ededed; font-size: x-large;">guigyoumusic@gmail.com</a>
                        </p>
                        <p class="text-center" style="color:#ededed; font-size: x-large;">
                            Tel: + 55 (31) 9229.9673
                        </p><br>
                        <p class="text-center">
                            <a target="_blank" href="https://www.instagram.com/gig2you/" class="fa fa-instagram" style="
                                margin-right: 10px;
                                margin-left: -5px;
                                width: 30px;
                                text-align: center;
                                text-decoration: none;
                                border-radius: 50%;
                            "></a>
                            <a target="_blank" href="https://www.facebook.com/guig.you" class="fa fa-facebook" style="
                                margin-left: 15px;
                                padding: 20px;
                                width: 30px;
                                text-align: center;
                                text-decoration: none;
                                border-radius: 50%;
                            "></a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}
{% block backbutton %}
{% endblock %}
{% block footer %}
{% endblock %}

src/django_project/apps/core/templates/core/other/faq.html
{% extends 'core/base/base.html' %}
{% load i18n %}
{% block extra_css %}
{{ form.media }}
    <style>
	body{
		background-color: #363636;
		color: #ededed;
	}
    .panel-body{
        {#background-color: #363636;#}
		color: #09581f;
        text-align: justify;
    }
    </style>
{% endblock %}
{% block subtitle %}FAQ's{% endblock %}
{% block content %}
        <div class="container">
            <div class="col-xs-12 col-md-10 pad-top-lg pad-bottom-lg col-md-offset-1">
                <header class="main-heading text-center row">
                    <div class="col-xs-12"><br>
                        <h2 class="heading" style="color: #ededed;"> {% trans 'FAQ' %} </h2>
                        <hr style="border-top: 3px solid #38892f" width="80px">
                    </div>
                </header>
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                    {% for faq in faqs %}
                      <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingOne">
                          <h4 class="panel-title">
                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ forloop.counter }}" aria-expanded="true" aria-controls="collapseOne">
                              {{ faq.title }}
                            </a>
                          </h4>
                        </div>
                        <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse " role="tabpanel" aria-labelledby="headingOne">
                          <div class="panel-body">
                            {{ faq.description }}
                          </div>
                        </div>
                      </div>
                    {% endfor %}
                </div>
            </div>
        </div>

{% endblock %}

src/django_project/apps/core/templates/core/other/index.html
{% extends 'core/base/base.html' %}
{% load static %}
{% load i18n %}
{% block extra_css %}
	<style>
		{#.bounce-1 {#}
		{#	animation-name: bounce-1;#}
		{#	animation-timing-function: ease-in-out;#}
		{#	position: absolute;#}
		{#	bottom: 0;#}
		{#	left: 50%;#}
		{#	margin-left: -21px;#}
		{#	z-index: 99;#}
		{#	color: white;#}
		{#	animation-duration: 0.75s;#}
		{#	animation-iteration-count: infinite;#}
		{#	font-size: 50px;#}
		{#	transform-origin: bottom;#}
		{#}#}
        {##}
		{#@keyframes bounce-1 {#}
		{#	0% {#}
		{#		transform: translateY(0);#}
		{#	}#}
		{#	50% {#}
		{#		transform: translateY(-25px);#}
		{#	}#}
		{#	100% {#}
		{#		transform: translateY(0);#}
		{#	}#}
		{#}#}



	</style>
{% endblock %}
{% block subtitle %} HomePage {% endblock %}

{% block content %}
	<!-- start of page main section -->
	<main id="main">
		<!-- start of main banner -->
		<section class="main-banner main-slider text-center">
			<!-- slide -->
			<div class="slide bg-img-full" style="background-image: url({% static 'images/cover_1920_1000.jpg' %});">
				<span class="bg-overlay"></span>
				<div class="container">
					<div class="row">
						<div class="col-xs-12">
							<div class="caption">
								<div class="holder">
{#									<h1 class="heading small3 text-uppercase">#}
{#										{% trans 'Gig2You' %}asd#}
{##}
{#									</h1>#}
                                    <div class="heading home_video_button_container">
{#                                        <iframe width="560" height="315" src="https://www.youtube.com/embed/BG00hLV__0w" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>#}
                                    <a href="https://www.youtube.com/embed/BG00hLV__0w?autoplay=1" class="play fa gig2you_home_video_button fa-play  lightbox fancybox.iframe text-center margin-zero"></a>
                                    </div>

                                    <a href="{% url 'core:preregister' %}" class="btn-green text-uppercase">{% trans 'Sign Up' %}</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section><!-- end of main banner -->

	</main><!-- end of page main section -->
	<!-- start of page footer -->
{% endblock %}
{% block backbutton %}

{% endblock %}

src/django_project/apps/core/templates/core/other/loggedhomepage.html
{% extends 'core/base/base_internal.html' %}
{% load static %}
{% load i18n %}
{% load user_profile_tags %}
{% block extra_css %}

{% endblock %}

{% block content %}
    {% if has_not_accepted_use_terms %}
        <div class="modal fade" id="terms-of-service" tabindex="-1" role="dialog" aria-labelledby="terms-of-service" style="display: none;" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="block block-themed block-transparent mb-0">
                        <div class="block-header bg-primary-dark">
                            <h3 class="block-title">{% trans 'Accept the platform Terms of Service to be able to use all its features!' %}</h3>
                            <div class="block-options">
                                <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                                    <i class="si si-close"></i>
                                </button>
                            </div>
                        </div>
                        <div class="block-content">
                            <p>{{ terms }}</p>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-alt-secondary" data-dismiss="modal">{% trans 'Not now' %}</button>
                        <a href="{% url 'core:acceptterms' %}" class="btn btn-alt-success">
                            <i class="fa fa-check"></i> {% trans 'I have read and accept the Terms of Service' %}
                        </a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
	<!-- start of page main section -->
	<h2 class="content-heading"> {% trans 'Upcoming Events' %} </h2>
	<div class="block" id="events_container">
		<div class="block-content">
			<table id="upcomingEvents" class="table table-striped nowrap" style="width:100%">
				<thead>
				<tr>
					<th class="text-center">{% trans 'Name' %}</th>
					<th class="text-center">{% trans 'Region' %}</th>
					<th class="text-center">{% trans 'Date' %}</th>
					<th class="text-center">{% trans 'Feat Artist' %}</th>
					<th class="text-center">{% trans 'Status MD' %}</th>
					<th class="text-center">{% trans 'Status Artist' %}</th>
					<th class="text-center">{% trans 'Status Payment' %}</th>
					<th class="text-center">{% trans 'Details' %}</th>
				</tr>
				</thead>
				<tbody>
				{% for event in events %}
					{% if event.is_past == False and event.is_active %}
						<tr>
							<td class="text-center">{{ event.name }}</td>
							<td class="text-center">{{ event.region }}</td>
							<td class="text-center" data-sort="{{ event.date|date:'Ymd' }}">{{ event.date }}</td>
							<td class="text-center">{{ event.artist.name }}</td>
							<td class="text-center">{{ event.get_confirmed_icon_html|safe }}</td>
							<td class="text-center">{{ event.get_artist_confirmation_icon_html|safe }}</td>
							<td class="text-center">{{ event.get_payment_confirmation_icon_html|safe }}</td>
							<td class="text-center"><a href="{% url 'core:event' event.id %}" class="btn btn-info"><i
									class="fa fa-eye table-button"></i> </a></td>
						</tr>
					{% endif %}
				{% endfor %}
				</tbody>
			</table>
			{% if user_type == 'producer' %}
				<div class="row text-center mar-top-sm">
					<a href="{% url 'core:newevent' %}"
					   class="btn btn-success text-uppercase">{% trans 'new event' %}</a>
				</div>
			{% endif %}
		</div>

	</div>
	{#		</div>#}


{% endblock %}

{% block extra_js %}
	<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
	<script>
		$(document).ready(function () {
		    jQuery('#terms-of-service').modal('show');
			$('#upcomingEvents').DataTable({
				"order": [[ 2, 'desc' ]],
				{#searching: false,#}
				{#paging: false,#}
				info: false,
				responsive: true,
				"scrollX": true,
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.20/i18n/Portuguese-Brasil.json"
                },
			});
		});

	</script>

{% endblock %}

src/django_project/apps/core/templates/core/other/pre_register.html
{% extends 'core/base/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block extra_css %}
    {{ form.media }}
    <style>
        body {
            background-color: #363636;
            color: #ededed;
        }
    </style>
{% endblock %}
{% block subtitle %}{% trans 'Pre Registration' %}{% endblock %}
{% block content %}
    <div class="block">
        <div class="col-xs-12 col-md-10 pad-top-lg col-md-offset-1">
            <header class="main-heading text-center row">
                <div class="block-header">
                    <h2 class="heading" style="color: #ededed;"> {% trans 'Pre Register Now!' %} </h2>
                    <hr style="border-top: 3px solid #38892f" width="80px">
                </div>
            </header>
            <div class="block-content">
                <form class="mb-10" data-toggle="validator" method="post">
                    <fieldset>
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-6">
                                {{ form.email|as_crispy_field }}
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-6">
                                {{ form.name|as_crispy_field }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-6">
                                {{ form.phone|as_crispy_field }}
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-6">
                                {{ form.whatsapp|as_crispy_field }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                {{ form.address|as_crispy_field }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-6">
                                {{ form.cep|as_crispy_field }}
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-6">
                                {{ form.doc_number|as_crispy_field }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-6">
                                {{ form.password|as_crispy_field }}
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-6">
                                {{ form.password_confirmation|as_crispy_field }}
                            </div>
                        </div>
                        <div id="msgSubmit" class="form-message hidden"></div>
                        <div class="row text-right">
                            <button class="btn btn-success " type="submit">{% trans 'Go!' %}</button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>

{% endblock %}
{% block footer %}

{% endblock %}

src/django_project/apps/core/templates/core/other/profle.html
{% extends 'core/base/base_internal.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
		<!-- start of main banner -->
	<h2 class="content-heading"> {% trans 'Edit your profile' %} </h2>
		<div class="block">
			<div class="block-content">
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
					<form class="mb-10" data-toggle="validator" method="post">
						<fieldset>
							{% csrf_token %}
							{{ form|crispy }}
							<div id="msgSubmit" class="form-message hidden"></div>
							<button class="btn btn-success" type="submit">{% trans 'Go!' %}</button>
						</fieldset>
					</form>
			</div>
		</div>

{% endblock %}