src/django_project/apps/core/urls.py
from django.urls import path
from django_project.apps.core import views

app_name = 'core'


urlpatterns = [
    path('home/', views.homepage, name='homepage'),
    path('profile/', views.profile, name='myprofile'),
    path('accept_terms/', views.accept_terms, name='acceptterms'),
    path('preregister/', views.producers_pre_register, name='preregister'),
    path('activate/<int:user_id>', views.activate_user, name='activate_user'),
    path('faq/', views.faq, name='faq'),
    path('message/<int:event_id>', views.send_message, name='sendmessage'),
    path('message/<int:comment_id>/delete/<int:event_id>', views.delete_message, name='deletemessage'),

    # musician-event confirmation / refusal
    path('musicianevent/confirmation/<int:musician_event_id>', views.add_musicians_confirmation, name='musicianconfirmation'),
    path('musicianevent/refusal/<int:musician_event_id>', views.add_musicians_refusal, name='musicianrefusal'),

    # musician related urls
    path('musician/management/', views.create_or_edit_musician, name='musicianmanagement'),
    path('musician/list/', views.musicians_list, name='musicianslist'),
    path('musician/delete/<int:musician_id>/', views.delete_musician, name='musiciandelete'),
    path('musician/addto/<int:event_id>/', views.add_musicians, name='addmusicians'),
    path('references/manage/<int:event_id>/', views.set_references_for_musicians, name='managereferencesforevent'),

    # event related urls
    path('event/history/', views.pastevents, name='pastevents'),
    path('event/<int:event_id>/', views.event, name='event'),
    path('event/new/', views.new_event, name='newevent'),
    path('event/confirm/<int:event_id>/', views.event_confirmed, name='eventconfirmed'),
    path('event/cancel/<int:event_id>/', views.event_cancelled, name='eventcancelled'),
    path('event/conclude/<int:event_id>/', views.conclude_event, name='eventconcluded'),
    path('event/paid/<int:event_id>/', views.event_paid, name='paymentconfirmed'),
    path('event/refused/<int:event_id>/', views.event_refused, name='refuseparticipation'),

    # artist song-management related urls
    path('song/list/', views.my_songs, name='my_songs'),
    path('song/manage/', views.manage_songs, name='songmanagement'),
    path('song/delete/<int:song_id>/', views.song_delete, name='songdelete'),
]

src/django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.utils.translation import ugettext as _
from django.shortcuts import render

admin.site.site_header = _('Gig2You - Administration')


def home(request):
    if request.user.is_staff:
        return redirect('admin:index')
    elif request.user.is_authenticated:
        return redirect('core:homepage')
    return render(request, 'core/other/index.html')


def contact(request):
    return render(request, 'core/other/contact.html')


def about(request):
    return render(request, 'core/other/about.html')

urlpatterns = [

    url(r'^impersonate/', include('impersonate.urls')),

    path('admin/', admin.site.urls, name='admin'),  # admin site

    path('', home, name='homepage'),
    path('about/', about, name='about'),

    path('app/', include('django_project.apps.core.urls', namespace='core')),
    path('contact/', contact, name='contact'),
    # auth
    path('accounts/login/',
         auth_views.LoginView.as_view(template_name='auth/login.html', redirect_authenticated_user=True),
         name='login'),

    path('logout/', auth_views.LogoutView.as_view(template_name='auth/logout.html'), name='logout'),

    # password reset
    path(
        'accounts/login/password_reset/',
        auth_views.PasswordResetView.as_view(template_name='auth/reset_form.html'),
        name='password_reset',
    ),
    path(
        'accounts/login/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name="auth/reset_done.html"),
        name='password_reset_done',
    ),
    path(
        'accounts/login/reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="auth/reset_confirm.html"),
        name='password_reset_confirm',
    ),
    path(
        'accounts/login/reset/done/',
        auth_views.PasswordResetCompleteView.as_view(template_name="auth/reset_complete.html"),
        name='password_reset_complete',
    ),
]

src/django_project/apps/django_app/models/base.py
"""Core Models to be used throughout the project
"""
from django.db import models

from django.utils.translation import ugettext_lazy as _

from django_project.apps.contrib.models.base_model import BaseModel

example_choices = (
    ('streams', 'streams'),
    ('users', 'users'),
    ('tracks', 'tracks'),
    ('sub_30_sec_streams', 'sub_30_sec_streams'),
    ('aggregatedstreams', 'aggregatedstreams'),
)


# Create your models here.
class ModelClass(BaseModel):
    name = models.CharField(max_length=10, default='')
    type = models.CharField(max_length=20, choices=example_choices)
    date = models.DateField()
    status = models.CharField(max_length=10, choices=(
        ('pending', 'pending'), ('error', 'error'), ('success', 'success')), default='pending')  # year or unknown

    class Meta:
        verbose_name = _('Example Model')
        verbose_name_plural = _('Example Models')

    def __str__(self):
        return str(self.type) + " - " + str(self.name)

src/django_project/apps/core/views.py
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist, FieldError
from django.db.models import Q
from django.http import HttpResponseNotFound, HttpResponseForbidden, HttpResponse, HttpResponseBadRequest, \
    HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from post_office import mail

from django_project.apps.core.models.base import ArtistSong, EventSong, FaqModel, Comment, has_accepted_use_terms
from .decorators import user_has_accepted_use_terms
from .forms import RawEventForm, CreateMusicianForm, UserForm, MusicianEventFormSetFactory, ArtistReferenceForm, \
    EventReferenceForm, CommentForm, UserBaseForm, ConcludeEventFormset, PostEventCommentForm
from django.utils.translation import ugettext as _

from .models import Event, Musician, MusicDirector, Artist, Producer, get_user_type, MusicianEvent, ArtistSong, \
    EventSong
from ...settings.terms_of_service import get_terms


# retorna o nivel de importancia do Faq, para fins de ordenação
def get_faq_importance(FaqModel):
    return FaqModel.importance


# retorna a data de criação do comentario
def get_date_order(Comment):
    return Comment.created_date


def faq(request):
    """
        Renders the FAQ page
    """
    context = dict()
    faqs = sorted(FaqModel.objects.all(), key=get_faq_importance)
    context['faqs'] = faqs
    return render(request, 'core/other/faq.html', context=context)


def producers_pre_register(request):
    """
        Faz o pre cadastro dos contratantes. O usuario eh criado como inativo ate que o SuperUsuario o avalie e ative
    """
    context = dict()
    if request.method == 'POST':
        form = UserBaseForm(data=request.POST)
        if form.is_valid():
            try:
                if not form.cleaned_data['password']:
                    raise FieldError
                user = User.objects.create(username=form.cleaned_data['email'], email=form.cleaned_data['email'],
                                           first_name=form.cleaned_data['name'], is_active=False)
                user.set_password(form.cleaned_data['password'])
                user.save()
                Producer.objects.create(
                    user_id=user.id,
                    phone=form.cleaned_data['phone'],
                    whatsapp=form.cleaned_data['whatsapp'],
                    address=form.cleaned_data['address'],
                    cep=form.cleaned_data['cep'],
                    doc_number=form.cleaned_data['doc_number'],
                    name=form.cleaned_data['name'],
                    email=form.cleaned_data['email'],
                )
                messages.success(request, _(
                    'Your profile has been submitted successfully! Our team will analyse it and you will receive an email if it is approved.'),
                                 extra_tags='alert')
            except FieldError:
                messages.warning(request, _('Password field is mandatory.'), extra_tags='alert')
        else:
            messages.warning(request, _('Fix the validation errors below before saving!'), extra_tags='alert')
    else:
        form = UserBaseForm()
    context['form'] = form
    return render(request, 'core/other/pre_register.html', context=context)


@login_required
@staff_member_required
def activate_user(request, user_id):
    """
        O SuperUsuario deve ativar usuarios de contratantes feitos atraves do pre-cadastro.
        Esta view eh ligada no admin do Produtor
    """
    user = User.objects.get(id=user_id)
    user.is_active = True
    user.save()
    send_mail_user_active(user.email, request)
    # redirecionando especificamente de volta para a pagina de edicao daquele produtor no admin
    # a funcao recebe como parametro uma string, e esta string eh prenchida com dados informados pelo format
    return HttpResponseRedirect(
        '{}producer/{}/change/'.format(request.build_absolute_uri(reverse('admin:app_list', args=('core',))),
                                       Producer.objects.get(user=user).id))


# ----------------------------
# MAIN views - comuns a todos
# ----------------------------
@login_required
def accept_terms(request):
    """
        Aceita os termos e condicoes de uso
    """
    user_type = get_user_type(request.user)
    user = User.objects.get(id=request.user.id)
    try:
        if user_type == 'artist':
            Artist.objects.get(user=user).accept_use_terms()
        if user_type == 'producer':
            Producer.objects.get(user=user).accept_use_terms()
        if user_type == 'musician':
            Musician.objects.get(user=user).accept_use_terms()
        if user_type == 'music_director':
            MusicDirector.objects.get(user=user).accept_use_terms()
    except ObjectDoesNotExist as e:
        return HttpResponse(e)
    return redirect('core:homepage')


@login_required
def homepage(request):
    """
        Renders the homepage
    """
    context = dict()
    user_type = get_user_type(request.user)
    context['user_type'] = user_type
    context['terms'] = get_terms(user_type)
    # exibe o modal de termos de uso caso o usuario ainda nao tenha aceito
    context['has_not_accepted_use_terms'] = not has_accepted_use_terms(request.user.id)
    # o conteudo do contexto varia para cada user type
    if user_type == 'artist':
        context['events'] = Event.objects.filter(
            Q(artist__user_id=request.user.id) | Q(producer__user_id=request.user.id))
        context['self'] = Artist.objects.get(user_id=request.user.id)
    elif user_type == 'producer':
        context['events'] = Event.objects.filter(producer__user_id=request.user.id)
        context['self'] = Producer.objects.get(user_id=request.user.id)
    elif user_type == 'music_director':
        music_director = MusicDirector.objects.get(user_id=request.user.id)
        context['events'] = music_director.event_set.all()
        context['musicians'] = music_director.musician_set.all()
        context['self'] = MusicDirector.objects.get(user_id=request.user.id)
    elif user_type == 'musician':
        # musician = Musician.objects.get(user_id=request.user.id)
        # musician_events = musician.musicianevent_set.prefetch_related().all()
        musician_events = MusicianEvent.objects.filter(musician__user_id=request.user.id).prefetch_related()
        context['musician_events'] = musician_events
        events = []
        for musician_event in musician_events:
            events.append(musician_event.event)
        context['events'] = events
        context['self'] = Musician.objects.get(user_id=request.user.id)

    # as particularidades de cada usuario no template sao tratadas dentro do mesmo
    return render(request, 'core/other/loggedhomepage.html', context=context)


@login_required
@user_has_accepted_use_terms
def profile(request):
    """
        Renders the profile template
    """
    user_type = get_user_type(request.user)
    if request.method == 'POST':
        # artistas tem que ver um template um pouco diferente, por causa da aceitacao de musicos
        is_artist = False
        if user_type == 'artist':
            is_artist = True
        form = UserForm(is_artist=(user_type == 'artist'), data=request.POST)
        if form.is_valid():
            user = User.objects.get(id=request.user.id)
            # user.email = form.cleaned_data['email']
            # user.username = form.cleaned_data['email']
            # user.first_name = form.cleaned_data['name']
            from django_project.apps.core.models.base import set_user_attribute
            set_user_attribute(request.user, 'email', form.cleaned_data['email'])
            set_user_attribute(request.user, 'name', form.cleaned_data['name'])
            set_user_attribute(request.user, 'phone', form.cleaned_data['phone'])
            set_user_attribute(request.user, 'address', form.cleaned_data['address'])
            set_user_attribute(request.user, 'cep', form.cleaned_data['cep'])
            set_user_attribute(request.user, 'doc_number', form.cleaned_data['doc_number'])

            if user_type == 'artist':
                set_user_attribute(request.user, 'phone', form.cleaned_data['phone'])
                set_user_attribute(request.user, 'accept_v', form.cleaned_data['accept_v'])
                set_user_attribute(request.user, 'accept_g', form.cleaned_data['accept_g'])
                set_user_attribute(request.user, 'accept_b', form.cleaned_data['accept_b'])
                set_user_attribute(request.user, 'accept_t', form.cleaned_data['accept_t'])
                set_user_attribute(request.user, 'accept_bt', form.cleaned_data['accept_bt'])
                set_user_attribute(request.user, 'accept_bvt', form.cleaned_data['accept_bvt'])
                set_user_attribute(request.user, 'accept_bvs', form.cleaned_data['accept_bvs'])
                set_user_attribute(request.user, 'accept_bvc', form.cleaned_data['accept_bvc'])

            if form.cleaned_data['password'] and form.cleaned_data['password'] != '':
                user.set_password(form.cleaned_data['password'])
            messages.success(request, _('Your profile has been updated successfully!'), extra_tags='alert')
            user.save()
    else:
        from django_project.apps.core.models.base import get_user_attribute
        # from django.http import HttpResponse
        if request.user.is_authenticated:
            initial = dict(
                user_id=request.user.id,
                email=request.user.get_username(),
                name=request.user.get_full_name(),
                whatsapp=get_user_attribute(request.user, 'whatsapp'),
                phone=get_user_attribute(request.user, 'phone'),

src/django_project/apps/core/templates/core/base/base.html
{% load static %}
{% load i18n %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<!DOCTYPE html>
<html lang="en">
<head>
	<!-- set the encoding of your site -->
	<meta charset="utf-8">
	<!-- set the viewport width and initial-scale on mobile devices -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- set the apple mobile web app capable -->
	<meta name="apple-mobile-web-app-capable" content="yes">
	<!-- set the HandheldFriendly -->
	<meta name="HandheldFriendly" content="True">
	<!-- set the apple mobile web app status bar style -->
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<!-- set the description -->
	{#    <meta name="description" content="Be - Startup Business HTML Template">#}
	{#    <meta name="keywords"#}
	{#          content="agency, Startup, bootstrap, business, corporate, creative, minimal, modern, onepage, personal, portfolio,  html5, responsive">#}
	{#    <meta name="author" content="Be - Startup Business HTML Template">#}
	<!-- Page Title -->
	<title>Gig2You - {% block subtitle %}{% endblock %}</title>
	<link rel="shortcut icon" type="image/png" href="{% static 'images/logo.png' %}">
	<!-- include the site stylesheet -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400%7CWork+Sans:300,400,500,600" rel="stylesheet">
	<!-- include the site stylesheet -->
	{#    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">#}
	<!-- include the site stylesheet -->
	<link rel="stylesheet" href="{% static 'css/fonts-icons.css' %}">
	<!-- include the site stylesheet -->
	<link rel="stylesheet" href="{% static 'css/plugin-resets.css' %}">
	<!-- include the site stylesheet -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}?0.0.0.1">
	<!-- include the site stylesheet -->
	<link rel="stylesheet" href="{% static 'css/responsive.css' %}">
	<!-- include the site stylesheet -->
	<link rel="stylesheet" href="{% static 'css/color.css' %}">
	<!-- include the datasheet -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

	<style>


        .home_video_button_container {
            width: 960px;
            height: 540px;
            max-width: 100%;
            background: url(" {% static 'images/home_video_backgroung.jpeg' %}");
            background-position: center;
            background-size: contain;
            background-repeat: no-repeat;

        }

        @media (max-width: 767px) {
            .home_video_button_container {
                width: 480px;
                height: 270px;
            }
        }


        .home_video_button_container .play {
            position: absolute;
            top: 50%;
        }

    </style>
    {% block extra_css %}
    {% endblock %}
    {% block extra_base_css %}
    {% endblock %}
</head>
<body>
{% if user.is_impersonate %}
	<a href="/impersonate/stop" class="btn btn-danger" style="padding: 10px; margin: 10px; z-index: 9999; bottom: 0; position: absolute;">PARAR IMPERSONATE</a>

{% endif %}
<!-- start of main page wrapper -->
<div id="wrapper">
	<!-- start of preloader -->
	<div class="loader-container" id="loader">
		<div class="spinner spinner-round"></div>
	</div><!-- end of preloader -->
	<div class="w1">
		<!-- start of page header -->
		<header id="header" class="{% block custom_header_class %}nospace{% endblock %}">
			<!-- header holder -->
			<div class="header-holder">
				<div class="container">
					<div class="row">
						<div class="col-xs-12">
							<!-- Page logo -->
							<div class="logo pull-left">
								<a href="{% url 'homepage' %}" class="img"><span class="custom-header-logo"></span></a></div>
							<div class="holder pull-right">
								<a href="#" class="menu-opener opener pull-right visible-xs">
									<i class="fa fa-bars"></i>
								</a>
								<!-- start of page navigation -->
								<nav id="nav" class="text-uppercase">
									<ul class="list-inline">
										{% block navbar %}
											{% if not user.is_authenticated %}
												<li>
													<a href="{% url 'homepage' %}">{% trans 'Home' %}</a>
												</li>
												<li>
													<a href="{% url 'about' %}">{% trans 'About Us' %}</a>
												</li>
												<li>
													<a href="{% url 'contact' %}">{% trans 'Contact us' %}</a>
												</li>
												<li>
													<a href="{% url 'core:homepage' %}">{% trans 'Sign in' %}</a>
												</li>
{#                                                <li>#}
{#													<a href="{% url 'core:preregister' %}">{% trans 'Pre Register Now!' %}</a>#}
{#												</li>#}
											{% else %}

											{% endif %}
											<li>

											</li>
										{% endblock %}
									</ul>
								</nav>
								<!-- end of page navigation -->
							</div>
						</div>
					</div>
				</div>
			</div>
		</header>
		<main id="main">
			{% block main_banner %}
			{% endblock %}
			<div class="container">
				{% include 'core/base/messages.html' %}
			</div>
			{% block content %}

			{% endblock %}
		</main>
		{% block backbutton %}
			<div class="container">
				<div class="col-sm-12 text-left mar-bottom-sm">
					<a class="btn btn-warning" onclick="history.back()"><i
							class="fa fa-chevron-left"></i> {% trans 'Back' %}</a>
				</div>
			</div>
		{% endblock %}
		{% block footer %}
			<footer id="footer">
				<div class="bg-dark2">
					<div class="container">
						<div class="row">
							<div class="col-xs-12 mar-bottom-xs mar-top-xs text-center">
								<a class="btn-green"
								   href="mailto:guigyoumusic@gmail.com?Subject=About%20Gig2You">{% trans 'Contact Us' %}</a>
							</div>
						</div>
					</div>
				</div>
				<!-- start of f-bottom -->
				<div class="bg-dark3 f-bottom">
					<div class="container">
						<div class="row">
							<div class="col-md-12 hidden-sm hidden-xs">
								<span class="pull-left">&copy Gig2You {% now "Y" %} {% trans ' All Rights Reserved.' %}</span>
                                <span class="pull-right" style="font-family: 'Open Sans', 'sans-serif'; font-size: large"><a href="{% url 'core:faq' %}"><i class="fa fa-question-circle"></i> FAQ</a></span>
							</div>
                            <div class="col-md-12 hidden-md hidden-lg	">
                                <span style="font-family: 'Open Sans', 'sans-serif'; font-size: large"><a href="{% url 'core:faq' %}"><i class="fa fa-question-circle"></i> FAQ</a></span>
							</div>
                            <br>
                            <div class="col-md-12 hidden-md hidden-lg	">
								<span>&copy Gig2You {% now "Y" %} {% trans ' All Rights Reserved.' %}</span>
                            </div>

						</div>
					</div>
				</div><!-- end of f-bottom -->
			</footer><!-- end of page footer -->
		{% endblock %}
	</div>
	<!-- Back Top of the page -->
	<span id="back-top" class="pe-7s-angle-up main-bg-color"></span>
</div><!-- end of main page wrapper -->
<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>
<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

{% block extra_js %}
	<script>
		$(document).ready(function () {
			$('#upcomingEvents').DataTable({
				searching: false,
				paging: false,
				info: false,
				responsive: true,
				"scrollX": true
			});
		});
	</script>
{% endblock %}
</body>
</html>

src/django_project/apps/core/templates/core/base/base_internal_bk.html
{% extends 'core/base/base.html' %}
{% load static %}
{% load i18n %}
{% block custom_header_class %}nospace{% endblock %}
{% block extra_base_css %}
<style>
	.panel-details-title{
		text-align: right;
		font-weight: 600;
	}
    @media only screen and (max-width: 770px) {
      .panel-details-title{
            text-align: left;
            font-weight: 600;
        }
    }

    .panel-title{
		text-align: left;
        margin-left: 15px;
	}
	.panel-details-description{
		text-align: justify;

	}
	.panel-details .row{
		margin-top: 10px;
	}

	.table-button{

	}

	.errorlist.nonfield{
		color: red;
	}
</style>


{% endblock %}

{% block main_banner %}
	<div class="page-header text-center bg-img-full" style="background-image: url({% static 'images/bg-title.jpg' %}); margin-top: 0;">
		<div class="pad-top-lg hidden-sm"></div>
		<span class="bg-overlay"></span>
		<div class="container">
			<div class="row pad-top-md pad-bottom-xs">
				<div class="col-xs-12">
					<h1 class="heading">{% block internal_page_title %}{% endblock %}</h1>
				</div>
			</div>
		</div>
		<div class="pad-top-lg hidden-sm"></div>
	</div>
{% endblock %}

src/django_project/apps/core/templates/core/base/messages.html
{% for message in messages %}
    <div class="row">

        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
    </div>
{% endfor %}