src/django_project/apps/core/urls.py
from django.urls import path
from django_project.apps.core import views

app_name = 'core'


urlpatterns = [
    path('home/', views.homepage, name='homepage'),
    path('profile/', views.profile, name='myprofile'),
    path('accept_terms/', views.accept_terms, name='acceptterms'),
    path('preregister/', views.producers_pre_register, name='preregister'),
    path('activate/<int:user_id>', views.activate_user, name='activate_user'),
    path('faq/', views.faq, name='faq'),
    path('message/<int:event_id>', views.send_message, name='sendmessage'),
    path('message/<int:comment_id>/delete/<int:event_id>', views.delete_message, name='deletemessage'),

    # musician-event confirmation / refusal
    path('musicianevent/confirmation/<int:musician_event_id>', views.add_musicians_confirmation, name='musicianconfirmation'),
    path('musicianevent/refusal/<int:musician_event_id>', views.add_musicians_refusal, name='musicianrefusal'),

    # musician related urls
    path('musician/management/', views.create_or_edit_musician, name='musicianmanagement'),
    path('musician/list/', views.musicians_list, name='musicianslist'),
    path('musician/delete/<int:musician_id>/', views.delete_musician, name='musiciandelete'),
    path('musician/addto/<int:event_id>/', views.add_musicians, name='addmusicians'),
    path('references/manage/<int:event_id>/', views.set_references_for_musicians, name='managereferencesforevent'),

    # event related urls
    path('event/history/', views.pastevents, name='pastevents'),
    path('event/<int:event_id>/', views.event, name='event'),
    path('event/new/', views.new_event, name='newevent'),
    path('event/confirm/<int:event_id>/', views.event_confirmed, name='eventconfirmed'),
    path('event/cancel/<int:event_id>/', views.event_cancelled, name='eventcancelled'),
    path('event/conclude/<int:event_id>/', views.conclude_event, name='eventconcluded'),
    path('event/paid/<int:event_id>/', views.event_paid, name='paymentconfirmed'),
    path('event/refused/<int:event_id>/', views.event_refused, name='refuseparticipation'),

    # artist song-management related urls
    path('song/list/', views.my_songs, name='my_songs'),
    path('song/manage/', views.manage_songs, name='songmanagement'),
    path('song/delete/<int:song_id>/', views.song_delete, name='songdelete'),
]

src/django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.utils.translation import ugettext as _
from django.shortcuts import render

admin.site.site_header = _('Gig2You - Administration')


def home(request):
    if request.user.is_staff:
        return redirect('admin:index')
    elif request.user.is_authenticated:
        return redirect('core:homepage')
    return render(request, 'core/other/index.html')


def contact(request):
    return render(request, 'core/other/contact.html')


def about(request):
    return render(request, 'core/other/about.html')

urlpatterns = [

    url(r'^impersonate/', include('impersonate.urls')),

    path('admin/', admin.site.urls, name='admin'),  # admin site

    path('', home, name='homepage'),
    path('about/', about, name='about'),

    path('app/', include('django_project.apps.core.urls', namespace='core')),
    path('contact/', contact, name='contact'),
    # auth
    path('accounts/login/',
         auth_views.LoginView.as_view(template_name='auth/login.html', redirect_authenticated_user=True),
         name='login'),

    path('logout/', auth_views.LogoutView.as_view(template_name='auth/logout.html'), name='logout'),

    # password reset
    path(
        'accounts/login/password_reset/',
        auth_views.PasswordResetView.as_view(template_name='auth/reset_form.html'),
        name='password_reset',
    ),
    path(
        'accounts/login/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name="auth/reset_done.html"),
        name='password_reset_done',
    ),
    path(
        'accounts/login/reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="auth/reset_confirm.html"),
        name='password_reset_confirm',
    ),
    path(
        'accounts/login/reset/done/',
        auth_views.PasswordResetCompleteView.as_view(template_name="auth/reset_complete.html"),
        name='password_reset_complete',
    ),
]

src/django_project/apps/core/views.py
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist, FieldError
from django.db.models import Q
from django.http import HttpResponseNotFound, HttpResponseForbidden, HttpResponse, HttpResponseBadRequest, \
    HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from post_office import mail

from django_project.apps.core.models.base import ArtistSong, EventSong, FaqModel, Comment, has_accepted_use_terms
from .decorators import user_has_accepted_use_terms
from .forms import RawEventForm, CreateMusicianForm, UserForm, MusicianEventFormSetFactory, ArtistReferenceForm, \
    EventReferenceForm, CommentForm, UserBaseForm, ConcludeEventFormset, PostEventCommentForm
from django.utils.translation import ugettext as _

from .models import Event, Musician, MusicDirector, Artist, Producer, get_user_type, MusicianEvent, ArtistSong, \
    EventSong
from ...settings.terms_of_service import get_terms


# retorna o nivel de importancia do Faq, para fins de ordenação
def get_faq_importance(FaqModel):
    return FaqModel.importance


# retorna a data de criação do comentario
def get_date_order(Comment):
    return Comment.created_date


def faq(request):
    """
        Renders the FAQ page
    """
    context = dict()
    faqs = sorted(FaqModel.objects.all(), key=get_faq_importance)
    context['faqs'] = faqs
    return render(request, 'core/other/faq.html', context=context)


def producers_pre_register(request):
    """
        Faz o pre cadastro dos contratantes. O usuario eh criado como inativo ate que o SuperUsuario o avalie e ative
    """
    context = dict()
    if request.method == 'POST':
        form = UserBaseForm(data=request.POST)
        if form.is_valid():
            try:
                if not form.cleaned_data['password']:
                    raise FieldError
                user = User.objects.create(username=form.cleaned_data['email'], email=form.cleaned_data['email'],
                                           first_name=form.cleaned_data['name'], is_active=False)
                user.set_password(form.cleaned_data['password'])
                user.save()
                Producer.objects.create(
                    user_id=user.id,
                    phone=form.cleaned_data['phone'],
                    whatsapp=form.cleaned_data['whatsapp'],
                    address=form.cleaned_data['address'],
                    cep=form.cleaned_data['cep'],
                    doc_number=form.cleaned_data['doc_number'],
                    name=form.cleaned_data['name'],
                    email=form.cleaned_data['email'],
                )
                messages.success(request, _(
                    'Your profile has been submitted successfully! Our team will analyse it and you will receive an email if it is approved.'),
                                 extra_tags='alert')
            except FieldError:
                messages.warning(request, _('Password field is mandatory.'), extra_tags='alert')
        else:
            messages.warning(request, _('Fix the validation errors below before saving!'), extra_tags='alert')
    else:
        form = UserBaseForm()
    context['form'] = form
    return render(request, 'core/other/pre_register.html', context=context)


@login_required
@staff_member_required
def activate_user(request, user_id):
    """
        O SuperUsuario deve ativar usuarios de contratantes feitos atraves do pre-cadastro.
        Esta view eh ligada no admin do Produtor
    """
    user = User.objects.get(id=user_id)
    user.is_active = True
    user.save()
    send_mail_user_active(user.email, request)
    # redirecionando especificamente de volta para a pagina de edicao daquele produtor no admin
    # a funcao recebe como parametro uma string, e esta string eh prenchida com dados informados pelo format
    return HttpResponseRedirect(
        '{}producer/{}/change/'.format(request.build_absolute_uri(reverse('admin:app_list', args=('core',))),
                                       Producer.objects.get(user=user).id))


# ----------------------------
# MAIN views - comuns a todos
# ----------------------------
@login_required
def accept_terms(request):
    """
        Aceita os termos e condicoes de uso
    """
    user_type = get_user_type(request.user)
    user = User.objects.get(id=request.user.id)
    try:
        if user_type == 'artist':
            Artist.objects.get(user=user).accept_use_terms()
        if user_type == 'producer':
            Producer.objects.get(user=user).accept_use_terms()
        if user_type == 'musician':
            Musician.objects.get(user=user).accept_use_terms()
        if user_type == 'music_director':
            MusicDirector.objects.get(user=user).accept_use_terms()
    except ObjectDoesNotExist as e:
        return HttpResponse(e)
    return redirect('core:homepage')


@login_required
def homepage(request):
    """
        Renders the homepage
    """
    context = dict()
    user_type = get_user_type(request.user)
    context['user_type'] = user_type
    context['terms'] = get_terms(user_type)
    # exibe o modal de termos de uso caso o usuario ainda nao tenha aceito
    context['has_not_accepted_use_terms'] = not has_accepted_use_terms(request.user.id)
    # o conteudo do contexto varia para cada user type
    if user_type == 'artist':
        context['events'] = Event.objects.filter(
            Q(artist__user_id=request.user.id) | Q(producer__user_id=request.user.id))
        context['self'] = Artist.objects.get(user_id=request.user.id)
    elif user_type == 'producer':
        context['events'] = Event.objects.filter(producer__user_id=request.user.id)
        context['self'] = Producer.objects.get(user_id=request.user.id)
    elif user_type == 'music_director':
        music_director = MusicDirector.objects.get(user_id=request.user.id)
        context['events'] = music_director.event_set.all()
        context['musicians'] = music_director.musician_set.all()
        context['self'] = MusicDirector.objects.get(user_id=request.user.id)
    elif user_type == 'musician':
        # musician = Musician.objects.get(user_id=request.user.id)
        # musician_events = musician.musicianevent_set.prefetch_related().all()
        musician_events = MusicianEvent.objects.filter(musician__user_id=request.user.id).prefetch_related()
        context['musician_events'] = musician_events
        events = []
        for musician_event in musician_events:
            events.append(musician_event.event)
        context['events'] = events
        context['self'] = Musician.objects.get(user_id=request.user.id)

    # as particularidades de cada usuario no template sao tratadas dentro do mesmo
    return render(request, 'core/other/loggedhomepage.html', context=context)


@login_required
@user_has_accepted_use_terms
def profile(request):
    """
        Renders the profile template
    """
    user_type = get_user_type(request.user)
    if request.method == 'POST':
        # artistas tem que ver um template um pouco diferente, por causa da aceitacao de musicos
        is_artist = False
        if user_type == 'artist':
            is_artist = True
        form = UserForm(is_artist=(user_type == 'artist'), data=request.POST)
        if form.is_valid():
            user = User.objects.get(id=request.user.id)
            # user.email = form.cleaned_data['email']
            # user.username = form.cleaned_data['email']
            # user.first_name = form.cleaned_data['name']
            from django_project.apps.core.models.base import set_user_attribute
            set_user_attribute(request.user, 'email', form.cleaned_data['email'])
            set_user_attribute(request.user, 'name', form.cleaned_data['name'])
            set_user_attribute(request.user, 'phone', form.cleaned_data['phone'])
            set_user_attribute(request.user, 'address', form.cleaned_data['address'])
            set_user_attribute(request.user, 'cep', form.cleaned_data['cep'])
            set_user_attribute(request.user, 'doc_number', form.cleaned_data['doc_number'])

            if user_type == 'artist':
                set_user_attribute(request.user, 'phone', form.cleaned_data['phone'])
                set_user_attribute(request.user, 'accept_v', form.cleaned_data['accept_v'])
                set_user_attribute(request.user, 'accept_g', form.cleaned_data['accept_g'])
                set_user_attribute(request.user, 'accept_b', form.cleaned_data['accept_b'])
                set_user_attribute(request.user, 'accept_t', form.cleaned_data['accept_t'])
                set_user_attribute(request.user, 'accept_bt', form.cleaned_data['accept_bt'])
                set_user_attribute(request.user, 'accept_bvt', form.cleaned_data['accept_bvt'])
                set_user_attribute(request.user, 'accept_bvs', form.cleaned_data['accept_bvs'])
                set_user_attribute(request.user, 'accept_bvc', form.cleaned_data['accept_bvc'])

            if form.cleaned_data['password'] and form.cleaned_data['password'] != '':
                user.set_password(form.cleaned_data['password'])
            messages.success(request, _('Your profile has been updated successfully!'), extra_tags='alert')
            user.save()
    else:
        from django_project.apps.core.models.base import get_user_attribute
        # from django.http import HttpResponse
        if request.user.is_authenticated:
            initial = dict(
                user_id=request.user.id,
                email=request.user.get_username(),
                name=request.user.get_full_name(),
                whatsapp=get_user_attribute(request.user, 'whatsapp'),
                phone=get_user_attribute(request.user, 'phone'),

src/django_project/apps/core/templates/core/artist/managesongs.html
<!--
    Template que renderiza o formulário de criar/editar referências. Visível aos artistas somente.
-->
{% extends 'core/base/base_internal.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
    <style>
        #spin{
            margin: 5px;
            display: none;
        }
    </style>
	<h2 class="content-heading"> {% trans 'Song management' %} </h2>
	<div class="block">
		<div class="block-content">

            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
			<form data-toggle="validator" method="post" enctype="multipart/form-data">
				<fieldset>
					{% csrf_token %}
					{{ form|crispy }}
					<div id="msgSubmit" class="form-message hidden"></div>
                    <div class="row">
                        <button id="go" class="btn btn-success" type="submit">{% trans 'Go!' %}</button>
                        <div id="spin">
                            <div class="spinner-border text-success" role="status">
                                <span class="sr-only">Loading...</span>
                            </div>
                            <span>{% trans 'Uploading file...' %}</span>
                        </div>
                    </div>
				</fieldset>
			</form>
		</div>
	</div>
	{% if song_id %}
		<div class="row text-right">
			<a href="{% url 'core:songdelete' song_id %}"
			   onclick="return confirm('{% trans 'Are you sure you want to delete this song?' %}');"
			   class="btn btn-danger"> {% trans 'Delete this song' %} </a>
		</div>
	{% endif %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
           document.getElementById('go').onclick =
               function () {
                   if(document.getElementById("id_file").files.length > 0 && document.getElementById("id_name").value && document.getElementById("id_notes").value){
                       document.getElementById("spin").style.display = 'block';
                   }
               };
        });
    </script>
{% endblock %}

src/django_project/apps/core/templates/core/artist/mysongs.html
<!--
    Template que renderiza a lista de referências do artista. Visível apenas aos artistas.
-->
{% extends 'core/base/base_internal.html' %}
{% load i18n %}
{% load static %}

{% block extra_css %}
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css">
{% endblock %}

{% block content %}
	<h2 class="content-heading"> {% trans 'My songs' %} </h2>
	<div class="block">
		<div class="block-content">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
			<table class="table table-striped nowrap" id="mySongsTable" style="width:100%">
				<thead>
				<tr>
					<th>{% trans 'Name' %}</th>
					<th>{% trans 'Links' %}</th>
					<th>{% trans 'File' %}</th>
					<th>{% trans 'Details' %}</th>
				</tr>
				</thead>
				<tbody>
				{% for song in songs %}
					<tr style="text-align:left; font-family: 'Open Sans', 'sans-serif';">
						<td>{{ song.name }}</td>
						<td>
							{{ song.links }}
						</td>
						<td>
							{% if song.file %}
								<a href="{{ song.file.url }}" class="btn btn-info"><i class="fa fa-download"></i></a>
							{% else %}
								<i class="fa fa-times" style="color: red"></i>
							{% endif %}
						</td>
						<td>
							<a href="{% url 'core:songmanagement' %}?song_id={{ song.id }}"
							   class="text-right btn btn-info"><i class="fa fa-pencil"></i></a>
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
		<div class="block-content bg-body-light text-center ">
			<a href="{% url 'core:songmanagement' %}" class="btn btn-success">{% trans 'New Song' %}</a>
		</div>
	</div>
{% endblock %}

{% block extra_js %}
	<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
	<script>
		$(document).ready(function () {
			console.log(1)
			$('#mySongsTable').DataTable({
				{#searching: false,#}
				{#paging: false,#}
				info: false,
				responsive: true,
				"scrollX": true
			});
		});

	</script>
{% endblock %}