src/django_project/apps/core/urls.py
from django.urls import path
from django_project.apps.core import views

app_name = 'core'


urlpatterns = [
    path('home/', views.homepage, name='homepage'),
    path('profile/', views.profile, name='myprofile'),
    path('accept_terms/', views.accept_terms, name='acceptterms'),
    path('preregister/', views.producers_pre_register, name='preregister'),
    path('activate/<int:user_id>', views.activate_user, name='activate_user'),
    path('faq/', views.faq, name='faq'),
    path('message/<int:event_id>', views.send_message, name='sendmessage'),
    path('message/<int:comment_id>/delete/<int:event_id>', views.delete_message, name='deletemessage'),

    # musician-event confirmation / refusal
    path('musicianevent/confirmation/<int:musician_event_id>', views.add_musicians_confirmation, name='musicianconfirmation'),
    path('musicianevent/refusal/<int:musician_event_id>', views.add_musicians_refusal, name='musicianrefusal'),

    # musician related urls
    path('musician/management/', views.create_or_edit_musician, name='musicianmanagement'),
    path('musician/list/', views.musicians_list, name='musicianslist'),
    path('musician/delete/<int:musician_id>/', views.delete_musician, name='musiciandelete'),
    path('musician/addto/<int:event_id>/', views.add_musicians, name='addmusicians'),
    path('references/manage/<int:event_id>/', views.set_references_for_musicians, name='managereferencesforevent'),

    # event related urls
    path('event/history/', views.pastevents, name='pastevents'),
    path('event/<int:event_id>/', views.event, name='event'),
    path('event/new/', views.new_event, name='newevent'),
    path('event/confirm/<int:event_id>/', views.event_confirmed, name='eventconfirmed'),
    path('event/cancel/<int:event_id>/', views.event_cancelled, name='eventcancelled'),
    path('event/conclude/<int:event_id>/', views.conclude_event, name='eventconcluded'),
    path('event/paid/<int:event_id>/', views.event_paid, name='paymentconfirmed'),
    path('event/refused/<int:event_id>/', views.event_refused, name='refuseparticipation'),

    # artist song-management related urls
    path('song/list/', views.my_songs, name='my_songs'),
    path('song/manage/', views.manage_songs, name='songmanagement'),
    path('song/delete/<int:song_id>/', views.song_delete, name='songdelete'),
]

src/django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.utils.translation import ugettext as _
from django.shortcuts import render

admin.site.site_header = _('Gig2You - Administration')


def home(request):
    if request.user.is_staff:
        return redirect('admin:index')
    elif request.user.is_authenticated:
        return redirect('core:homepage')
    return render(request, 'core/other/index.html')


def contact(request):
    return render(request, 'core/other/contact.html')


def about(request):
    return render(request, 'core/other/about.html')

urlpatterns = [

    url(r'^impersonate/', include('impersonate.urls')),

    path('admin/', admin.site.urls, name='admin'),  # admin site

    path('', home, name='homepage'),
    path('about/', about, name='about'),

    path('app/', include('django_project.apps.core.urls', namespace='core')),
    path('contact/', contact, name='contact'),
    # auth
    path('accounts/login/',
         auth_views.LoginView.as_view(template_name='auth/login.html', redirect_authenticated_user=True),
         name='login'),

    path('logout/', auth_views.LogoutView.as_view(template_name='auth/logout.html'), name='logout'),

    # password reset
    path(
        'accounts/login/password_reset/',
        auth_views.PasswordResetView.as_view(template_name='auth/reset_form.html'),
        name='password_reset',
    ),
    path(
        'accounts/login/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name="auth/reset_done.html"),
        name='password_reset_done',
    ),
    path(
        'accounts/login/reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="auth/reset_confirm.html"),
        name='password_reset_confirm',
    ),
    path(
        'accounts/login/reset/done/',
        auth_views.PasswordResetCompleteView.as_view(template_name="auth/reset_complete.html"),
        name='password_reset_complete',
    ),
]

src/django_project/apps/core/views.py
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist, FieldError
from django.db.models import Q
from django.http import HttpResponseNotFound, HttpResponseForbidden, HttpResponse, HttpResponseBadRequest, \
    HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from post_office import mail

from django_project.apps.core.models.base import ArtistSong, EventSong, FaqModel, Comment, has_accepted_use_terms
from .decorators import user_has_accepted_use_terms
from .forms import RawEventForm, CreateMusicianForm, UserForm, MusicianEventFormSetFactory, ArtistReferenceForm, \
    EventReferenceForm, CommentForm, UserBaseForm, ConcludeEventFormset, PostEventCommentForm
from django.utils.translation import ugettext as _

from .models import Event, Musician, MusicDirector, Artist, Producer, get_user_type, MusicianEvent, ArtistSong, \
    EventSong
from ...settings.terms_of_service import get_terms


# retorna o nivel de importancia do Faq, para fins de ordenação
def get_faq_importance(FaqModel):
    return FaqModel.importance


# retorna a data de criação do comentario
def get_date_order(Comment):
    return Comment.created_date


def faq(request):
    """
        Renders the FAQ page
    """
    context = dict()
    faqs = sorted(FaqModel.objects.all(), key=get_faq_importance)
    context['faqs'] = faqs
    return render(request, 'core/other/faq.html', context=context)


def producers_pre_register(request):
    """
        Faz o pre cadastro dos contratantes. O usuario eh criado como inativo ate que o SuperUsuario o avalie e ative
    """
    context = dict()
    if request.method == 'POST':
        form = UserBaseForm(data=request.POST)
        if form.is_valid():
            try:
                if not form.cleaned_data['password']:
                    raise FieldError
                user = User.objects.create(username=form.cleaned_data['email'], email=form.cleaned_data['email'],
                                           first_name=form.cleaned_data['name'], is_active=False)
                user.set_password(form.cleaned_data['password'])
                user.save()
                Producer.objects.create(
                    user_id=user.id,
                    phone=form.cleaned_data['phone'],
                    whatsapp=form.cleaned_data['whatsapp'],
                    address=form.cleaned_data['address'],
                    cep=form.cleaned_data['cep'],
                    doc_number=form.cleaned_data['doc_number'],
                    name=form.cleaned_data['name'],
                    email=form.cleaned_data['email'],
                )
                messages.success(request, _(
                    'Your profile has been submitted successfully! Our team will analyse it and you will receive an email if it is approved.'),
                                 extra_tags='alert')
            except FieldError:
                messages.warning(request, _('Password field is mandatory.'), extra_tags='alert')
        else:
            messages.warning(request, _('Fix the validation errors below before saving!'), extra_tags='alert')
    else:
        form = UserBaseForm()
    context['form'] = form
    return render(request, 'core/other/pre_register.html', context=context)


@login_required
@staff_member_required
def activate_user(request, user_id):
    """
        O SuperUsuario deve ativar usuarios de contratantes feitos atraves do pre-cadastro.
        Esta view eh ligada no admin do Produtor
    """
    user = User.objects.get(id=user_id)
    user.is_active = True
    user.save()
    send_mail_user_active(user.email, request)
    # redirecionando especificamente de volta para a pagina de edicao daquele produtor no admin
    # a funcao recebe como parametro uma string, e esta string eh prenchida com dados informados pelo format
    return HttpResponseRedirect(
        '{}producer/{}/change/'.format(request.build_absolute_uri(reverse('admin:app_list', args=('core',))),
                                       Producer.objects.get(user=user).id))


# ----------------------------
# MAIN views - comuns a todos
# ----------------------------
@login_required
def accept_terms(request):
    """
        Aceita os termos e condicoes de uso
    """
    user_type = get_user_type(request.user)
    user = User.objects.get(id=request.user.id)
    try:
        if user_type == 'artist':
            Artist.objects.get(user=user).accept_use_terms()
        if user_type == 'producer':
            Producer.objects.get(user=user).accept_use_terms()
        if user_type == 'musician':
            Musician.objects.get(user=user).accept_use_terms()
        if user_type == 'music_director':
            MusicDirector.objects.get(user=user).accept_use_terms()
    except ObjectDoesNotExist as e:
        return HttpResponse(e)
    return redirect('core:homepage')


@login_required
def homepage(request):
    """
        Renders the homepage
    """
    context = dict()
    user_type = get_user_type(request.user)
    context['user_type'] = user_type
    context['terms'] = get_terms(user_type)
    # exibe o modal de termos de uso caso o usuario ainda nao tenha aceito
    context['has_not_accepted_use_terms'] = not has_accepted_use_terms(request.user.id)
    # o conteudo do contexto varia para cada user type
    if user_type == 'artist':
        context['events'] = Event.objects.filter(
            Q(artist__user_id=request.user.id) | Q(producer__user_id=request.user.id))
        context['self'] = Artist.objects.get(user_id=request.user.id)
    elif user_type == 'producer':
        context['events'] = Event.objects.filter(producer__user_id=request.user.id)
        context['self'] = Producer.objects.get(user_id=request.user.id)
    elif user_type == 'music_director':
        music_director = MusicDirector.objects.get(user_id=request.user.id)
        context['events'] = music_director.event_set.all()
        context['musicians'] = music_director.musician_set.all()
        context['self'] = MusicDirector.objects.get(user_id=request.user.id)
    elif user_type == 'musician':
        # musician = Musician.objects.get(user_id=request.user.id)
        # musician_events = musician.musicianevent_set.prefetch_related().all()
        musician_events = MusicianEvent.objects.filter(musician__user_id=request.user.id).prefetch_related()
        context['musician_events'] = musician_events
        events = []
        for musician_event in musician_events:
            events.append(musician_event.event)
        context['events'] = events
        context['self'] = Musician.objects.get(user_id=request.user.id)

    # as particularidades de cada usuario no template sao tratadas dentro do mesmo
    return render(request, 'core/other/loggedhomepage.html', context=context)


@login_required
@user_has_accepted_use_terms
def profile(request):
    """
        Renders the profile template
    """
    user_type = get_user_type(request.user)
    if request.method == 'POST':
        # artistas tem que ver um template um pouco diferente, por causa da aceitacao de musicos
        is_artist = False
        if user_type == 'artist':
            is_artist = True
        form = UserForm(is_artist=(user_type == 'artist'), data=request.POST)
        if form.is_valid():
            user = User.objects.get(id=request.user.id)
            # user.email = form.cleaned_data['email']
            # user.username = form.cleaned_data['email']
            # user.first_name = form.cleaned_data['name']
            from django_project.apps.core.models.base import set_user_attribute
            set_user_attribute(request.user, 'email', form.cleaned_data['email'])
            set_user_attribute(request.user, 'name', form.cleaned_data['name'])
            set_user_attribute(request.user, 'phone', form.cleaned_data['phone'])
            set_user_attribute(request.user, 'address', form.cleaned_data['address'])
            set_user_attribute(request.user, 'cep', form.cleaned_data['cep'])
            set_user_attribute(request.user, 'doc_number', form.cleaned_data['doc_number'])

            if user_type == 'artist':
                set_user_attribute(request.user, 'phone', form.cleaned_data['phone'])
                set_user_attribute(request.user, 'accept_v', form.cleaned_data['accept_v'])
                set_user_attribute(request.user, 'accept_g', form.cleaned_data['accept_g'])
                set_user_attribute(request.user, 'accept_b', form.cleaned_data['accept_b'])
                set_user_attribute(request.user, 'accept_t', form.cleaned_data['accept_t'])
                set_user_attribute(request.user, 'accept_bt', form.cleaned_data['accept_bt'])
                set_user_attribute(request.user, 'accept_bvt', form.cleaned_data['accept_bvt'])
                set_user_attribute(request.user, 'accept_bvs', form.cleaned_data['accept_bvs'])
                set_user_attribute(request.user, 'accept_bvc', form.cleaned_data['accept_bvc'])

            if form.cleaned_data['password'] and form.cleaned_data['password'] != '':
                user.set_password(form.cleaned_data['password'])
            messages.success(request, _('Your profile has been updated successfully!'), extra_tags='alert')
            user.save()
    else:
        from django_project.apps.core.models.base import get_user_attribute
        # from django.http import HttpResponse
        if request.user.is_authenticated:
            initial = dict(
                user_id=request.user.id,
                email=request.user.get_username(),
                name=request.user.get_full_name(),
                whatsapp=get_user_attribute(request.user, 'whatsapp'),
                phone=get_user_attribute(request.user, 'phone'),

src/django_project/apps/core/templates/core/event/detail_blocks/block_comment_section.html
<!--
    Bloco de comentários do evento, usados para que o artista e o diretor musical possam se comunicar de forma fácil.
-->
{% load static %}
{% load i18n %}
{% load user_profile_tags %}

<!--
    somente podem ocorrer comentarios se:
    a) o user logado for um artista, o evento estiver ativo (nao tiver sido cancelado) e o artista nao for o produtor do evento
    b) o user logado for um diretor musical e o evento estiver ativo
    c) qualquer um dos dois casos acima E:
        c.1) o evento ainda nao tiver acontecido (vide documentacao do metodo has_happened)
        c.2) o evento tiver acontecido mas ainda nao tiver sido finalizado pelo produtor
-->
{% if event.is_active %}
    {% if user_type == 'artist' and not artist_is_producer or user_type == 'artist' and artist_is_producer and artist_is_event_artist or user_type == 'music_director' %}
        {% if not event.has_happened or event.has_happened and not event.is_finalized %}
            <div class="row" id="commentsection">
                <div class="col-md-12">
                    <div class="block block-default">
                        <div class="block-header block-header-default">
                            <h3 class="block-title">
                                {% trans 'Comments' %}
                            </h3>
                        </div>
                        <div class="block-content block-details">
                            <span class="text-muted"> {% trans 'In this section you can chat with the music director/artist of this event. Just type a message below, send it, and chat away!' %}</span><br><br>
    <!--                        lista os comentarios ja existentes com a estilizacao em formato de 'chat' -->
                            {% for comment in comments %}
    <!--                        se o comentario for seu, permitir deletar e estilizar a bolha do chat de acordo -->
                                {% if comment.author.email == user.email %}
                                    <div class="row">
                                        <div class="col-md-6"></div>
                                        <div class="col-md-5 comment">
                                            <span><strong>{{ comment.author.first_name }}</strong></span>
                                            <a onclick=" return confirm('{% trans 'Are you sure you want to delete this message?' %}');"
                                               class="text-danger" id="right"
                                               href="{% url 'core:deletemessage' comment.id event.id %} "><i
                                                    class="fa fa-times"></i></a>
                                            <br>
                                            <span>{{ comment.message }}</span><br>
                                            <small id="right">{{ comment.created_date.date }}</small><br>
                                        </div>
                                    </div>
    <!--                                se o comentario nao for seu, apenas estilizar a bolha de acordo -->
                                {% else %}
                                    <div class="row">
                                        <div class="col-md-5 comment theirs">
                                            <span><strong>{{ comment.author.first_name }}</strong></span>
                                            <br>
                                            <span>{{ comment.message }}</span><br>
                                            <small id="right">{{ comment.created_date.date }}</small><br>
                                        </div>
                                        <div class="col-md-6"></div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                        <div class="block-content bg-body-light message-section">
                            <form id="comments" action="{% url 'core:sendmessage' event.id %}" method="post">
                                {% csrf_token %}
                                <div class="form-group message-type">
                                            <textarea class="form-control" name="message"
                                                      placeholder="{% trans 'Type your message here...' %}"></textarea>
    <!--                            o ctrl+enter para enviar nao funciona em aparelhos moveis, entao so mostra essa mensagem
                                    caso o usuario nao esteja em um dispositivo movel
    -->
                                    {% if not mobileAndTabletCheck %}
                                        <small>{% trans 'You can press Ctrl+Enter to send' %}</small>
                                    {% endif %}
                                </div>
                                <div class="text-right">
                                    <input class="btn btn-success" type="submit" value="{% trans 'Send' %}">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endif %}
{% endif %}

src/django_project/apps/core/templates/core/event/detail_blocks/block_producer_exclusive.html
<!--
    Bloco de informações pertinentes ao Contratante apenas. Basicamente renderiza os botões de Cancelamento e
     Conclusão do evento, caso passem nas condições descritas.
-->
{% load static %}
{% load i18n %}
{% load user_profile_tags %}
<!--
    o evento so pode ser cancelado pelo produtor do evento (artista ou não), e somente se a data dele ainda não
    houver passado (metodo is_past).
-->
{% if user_type == 'producer' and not event.is_past or user_type == 'artist' and not event.is_past and artist_is_producer %}
    {% if event.get_confirmed_is_pending or event.get_artist_confirmation_is_pending or event.get_everyone_declined %}
        <div class="row">
            <div class="col-md-12">
                <div class="block block-default">
                    <div class="block-header block-header-default">
                        <h3 class="block-title">
                            {% trans 'Cancel' %}
                        </h3>
                    </div>
                    <div class="block-content block-details">
                        <form style="margin-bottom: 0" method="post" id="cancelEvent"
                              action="{% url 'core:eventcancelled' event.id %}"
                              onsubmit="return confirm('{% trans 'Are you sure you want to cancel this entire event? This cannot be undone!' %}');">
                            {% csrf_token %}
                            <button type="submit"
                                    class="btn btn-danger"> {% trans 'Cancel event' %} </button>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    {% endif %}
{% endif %}
<!--
    o evento so pode ser concluido pelo produtor do evento (artista ou nao), e somente se o evento houver passado, com
    artista e dm confirmados (metodo has_happened), e caso ele ainda não tenha sido concluido (variavel is_finalized).
-->
{% if user_type == 'producer' and event.has_happened and not event.is_finalized or user_type == 'artist' and artist_is_producer and event.has_happened and not event.is_finalized %}
    <div class="row">
        <div class="col-md-12">
            <div class="block block-default">
                <div class="block-header block-header-default">
                    <h3 class="block-title">
                        {% trans 'Conclude Event' %}
                    </h3>
                </div>
                <div class="block-content block-details">
                    <a class="btn btn-primary"
                       href="{% url 'core:eventconcluded' event.id %}">{% trans 'Conclude event' %}</a>
                </div>
            </div>
        </div>
    </div>
{% endif %}

src/django_project/apps/core/templates/core/event/detail_blocks/sub_block_confirm_participation.html
<!--
    Bloco que renderiza os botões de confirmação e recusa de participação no evento. Cada tipo de usuário é redire-
     cionado para uma view diferente. Este bloco somente não é visível para o Contratante.
-->
{% load static %}
{% load i18n %}
{% load user_profile_tags %}

{% if not event.is_past %}
    <div class="block-content bg-body-light">
        <div class="row">
            <!-- music director confirmation section -->
            {% if user_type == 'music_director' %}
                {% if event.is_confirmed %}
                    <span class="glyphicon glyphicon-ok-circle event-confirmation"></span>
                {% else %}
                    <div class="col-sm-6 col-md-6 text-left">
                        <form style="margin-bottom: 0" method="post" id="cancelEvent"
                              action="{% url 'core:refuseparticipation' event.id %}"
                              onsubmit="return confirm('{% trans 'Are you sure you want to refuse to participate on this event?' %}');">
                            {% csrf_token %}
                            <button type="submit"
                                    class="btn btn-danger"> {% trans 'Refuse participation' %} </button>
                        </form>
                    </div>
                    <div class="col-sm-6 col-md-6 text-right">
                        <form style="margin-bottom: 0" method="post"
                              action="{% url 'core:eventconfirmed' event.id %}"
                              onsubmit="return confirm('{% trans 'Are you sure you want to confirm your participation in this event? This cannot be undone!' %}');">
                            {% csrf_token %}
                            <button type="submit"
                                    class="btn btn-success"
                                    name="button">{% trans 'Confirm participation' %}</button>
                        </form>
                    </div>
                {% endif %}
            <!-- artist confirmation section -->
            {% elif user_type == 'artist' and not artist_is_producer or user_type == 'artist' and artist_is_producer and artist_is_event_artist %}
                {% if not event.get_artist_confirmation_is_pending %}
                    <span class="glyphicon glyphicon-ok-circle event-confirmation"></span>
                {% else %}
                    <div class="col-sm-6 col-md-6 text-left">
                        <form style="margin-bottom: 0" method="post"
                              action="{% url 'core:eventconfirmed' event.id %}"
                              onsubmit="return confirm('{% trans 'Are you sure you want to confirm your participation in this event? This cannot be undone!' %}');">
                            {% csrf_token %}
                            <button type="submit"
                                    class="btn btn-success"
                                    name="button">{% trans 'Confirm participation' %}</button>
                        </form>
                    </div>
                    <div class="col-sm-6 col-md-6 text-right">
                        <form style="margin-bottom: 0" method="post" id="cancelEvent"
                              action="{% url 'core:refuseparticipation' event.id %}"
                              onsubmit="return confirm('{% trans 'Are you sure you want to refuse to participate on this event?' %}');">
                            {% csrf_token %}
                            <button type="submit"
                                    class="btn btn-danger"> {% trans 'Refuse participation' %} </button>
                        </form>
                    </div>
                {% endif %}
            <!-- musician confirmation section -->
            {% elif user_type == 'musician' %}
                {% if musician_events.confirmation != 'PE' %}
                    {#										{{ event.get_status_code_icon_html(musician_events.confirmation) }}#}
                    {#                                        <span class="fa fa-check-circle text-success"></span>#}
                {% else %}
                    <div class="col-sm-6 col-md-6 text-left">
                        <form style="margin-bottom: 0" method="post"
                              action="{% url 'core:musicianconfirmation' musician_events.id %}"
                              onsubmit="return confirm('{% trans 'Are you sure you want to confirm your participation in this event? This cannot be undone!' %}');">
                            {% csrf_token %}
                            <button type="submit"
                                    class="btn btn-success"
                                    name="button">{% trans 'Confirm participation' %}</button>
                        </form>
                    </div>
                    <div class="col-sm-6 col-md-6 text-right">
                        <form style="margin-bottom: 0" method="post" id="cancelEvent"
                              action="{% url 'core:musicianrefusal' musician_events.id %}"
                              onsubmit="return confirm('{% trans 'Are you sure you want to refuse to participate on this event?' %}');">
                            {% csrf_token %}
                            <button type="submit"
                                    class="btn btn-danger"> {% trans 'Refuse participation' %} </button>
                        </form>
                    </div>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endif %}

src/django_project/apps/core/templates/core/event/detail_blocks/sub_block_dm_assign_musicians.html
<!--
    Bloco responsável por permitir ao Diretor Musical atribuir sua banda para cada posição especificada pelo Contratante
-->
{% load static %}
{% load i18n %}
{% load user_profile_tags %}

<div class="row">
        <div class="col-md-12">
            <div class="block block-default">
                <div class="block-header block-header-default">
                    <h3 class="block-title">
                        {% trans 'Musicians' %}
                    </h3>
                </div>
                <div class="block-content block-details">
                    <div class="row">
                        <div class="col-xs-3 col-md-3 block-details-title">{% trans 'Necessary musicians' %}:</div>
                        <div class="col-xs-9 col-md-9 block-details-description">
                            <ul>
                                {% for musician_event in musician_events %}
                                    {% if musician_event.parent_musician_event %}
                                        <li style="list-style-type:none">
                                        <ul>
                                    {% endif %}
                                <li>
                                    {{ musician_event.instrument_for_humans }} -
                                    {% if musician_event.musician %}
                                        {{ musician_event.musician }}
                                        {% if musician_event.confirmation == event.get_confirmed_status_code %}
                                            <span class="fa fa-check-circle text-success"></span>
                                        {% elif musician_event.confirmation == event.get_pending_status_code %}
                                            <span class="fa fa-clock-o text-warning"></span>
                                        {% elif musician_event.confirmation == event.get_refused_status_code %}
                                            <span class="fa fa-times-circle text-danger"></span>
                                        {% endif %}
                                    {% else %}
                                        {% trans 'n/a' %}
                                    {% endif %}
                                </li>

                                {% if musician_event.parent_musician_event %}
                                    </li>
                                    </ul>
                                {% endif %}
                                {% endfor %}

                            </ul>
                        </div>
                    </div>
                </div>
                {% if not event.is_past and event.is_active %}
                    <div class="block-content bg-body-light text-center">
                        <a href="{% url 'core:addmusicians' event.id %}"
                           class="btn btn-info">{% trans 'Add musicians' %}</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>